House controller
yashodhicy/Final-capstone-back-end pull request #17
Opened 2023-09-22 18:47 UTC by yashodhicy

### In this milestone I created
👶🏻 House controller
👶🏻And all the necessary actions and respective endpoints

![image](https://github.com/yashodhicy/Final-capstone-back-end/assets/116276432/097af5aa-fb7b-4289-8f1b-8acf814de3e5)

2023-09-22 21:00 UTC, Mahamadou-Nouridine requested changes
Hey @yashodhicy, you have done a nice job so far, congratulations. But there still are some issues that need improvement. Kindly check the comments below. You can skip the optional ones but it's highly recommended to take them into consideration as well
![170491251-b1add8ba-b18f-4648-a893-20e510d957fd](https://github.com/yashodhicy/Final-capstone-back-end/assets/98597449/24ea6109-be1b-4926-813c-94c48c7a1e38)

2023-09-22 21:00 UTC, Mahamadou-Nouridine commented on config/database.yml
[Optional] You don't need to specify the username and password, they are supposed to be private 😉.

2023-09-22 21:00 UTC, Mahamadou-Nouridine commented on app/controllers/api/v1/houses_controller.rb
> +  end
[Optional] We don't need the new action since we are not creating a rails standalone application so there is no need for a route for sending the form HTML

2023-09-22 21:00 UTC, Mahamadou-Nouridine commented on app/controllers/api/v1/houses_controller.rb
> +    @houses = House.all
We need the current user houses not all the houses for security purpose

2023-09-23 08:10 UTC, yashodhicy commented on app/controllers/api/v1/houses_controller.rb
> +    @houses = House.all
But for this application, the purpose is to show all the houses and able to rent the houses.

2023-09-23 10:10 UTC, Mahamadou-Nouridine approved these changes
You've done a great job so far @yashodhicy, your changes are approved, there's nothing to say the than it's time to approve it :shipit: 
![207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124](https://github.com/yashodhicy/Final-capstone-back-end/assets/98597449/cb788aad-26a7-4f70-b440-03eb6ef96aa9)

2023-09-23 11:28 UTC, merged