Final group capstone - Book an House
yashodhicy/Final-capstone-back-end pull request #22
Opened 2023-10-04 15:29 UTC by yashodhicy

### In this pull request our team created all Api requests according to requirements:

🌺 Add authentication
🌺 Add house api end points to create , view , show delete
🌺 Add reservation api end points to create , view 
🌺 Install linter errors and fixed those

🌺api documentation link
https://house-rental-8mh7.onrender.com/api-docs/index.html

🌺 Front end app pull link
https://github.com/yashodhicy/Final-capstone-front-end/pull/28

2023-10-04 18:19 UTC, mcrd25 requested changes
Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good routes 👍 
- Documentation present 👍 
- Good README 👍 
- Application works functionally 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Should always have positive and negative tests to ensure it works the way you expect it. Eg. What do you expect the output to be when it's not valid or when valid etc.
Consider making all your tests more extensive, not just this one. For this simple application, it may not catch a possible crippling bug, but in bigger applications, it definitely can. Consider this for all projects moving forward.

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_Also, you do not have to implement all requested changes, as this is up to you in the end, but I strongly recommend you implement them._

2023-10-04 18:19 UTC, mcrd25 commented on app/models/user.rb
> +  validates :username, :email, presence: true
[OPTIONAL] Consider a length validation for username

2023-10-04 18:19 UTC, mcrd25 commented on app/controllers/api/v1/houses_controller.rb
> +    current_user
`current_user` is called but never user, please remove

2023-10-04 18:19 UTC, mcrd25 commented on app/controllers/api/v1/houses_controller.rb
> +    @userhouses = user.houses.all
would it not be better simply call `@userhouses = current_user.houses.all`

2023-10-04 18:19 UTC, mcrd25 commented on app/controllers/api/v1/houses_controller.rb
> +    @house = House.find(params[:id])
Not seeing any error handling in the case where house cannot be found by given id

2023-10-04 18:19 UTC, mcrd25 commented on app/controllers/api/v1/houses_controller.rb
> +    @house = House.find(params[:id])
[OPTIONAL] This piece of code is also used in `destroy` maybe you can abstract it  into a method and make a `before_action` method

2023-10-05 04:58 UTC, yashodhicy commented on app/models/user.rb
> +  validates :username, :email, presence: true
Thank you

2023-10-05 04:58 UTC, yashodhicy commented on app/controllers/api/v1/houses_controller.rb
> +    current_user
Thank you

2023-10-05 06:12 UTC, Meltrust approved these changes
_note: This review outcome only applies to the backend repo.  Kindly, go to the [frontend ](https://github.com/yashodhicy/Final-capstone-front-end/pull/28)repo to see the review for that project._

#### Hi @yashodhicy,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)





Cheers and Happy coding!👏👏👏


------

2023-10-05 06:52 UTC, Mahamadou-Nouridine commented
Thank you @Meltrust

2023-10-06 07:04 UTC, merged